apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloudflared
  name: cloudflared-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
        - 1.1.1.1
        searches:
        - default.svc.cluster.local
        options:
        - name: ndots
          value: "5"
      containers:
      - command:
        - cloudflared
        - tunnel
        # In a k8s environment, the metrics server needs to listen outside the pod it runs on.
        # The address 0.0.0.0:2000 allows any pod in the namespace.
        - --metrics
        - 0.0.0.0:2000
        - run
        args:
        - --token
        - $(CF_TOKEN)
        image: cloudflare/cloudflared:latest
        name: cloudflared
        imagePullPolicy: Never
        env:
        - name: CF_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflared-token
              key: CF_TOKEN
        livenessProbe:
          httpGet:
          # Cloudflared has a /ready endpoint which returns 200 if and only if
          # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10